{
 "title": "NATS JetStream",
 "description": "NATS JetStream Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prom_ds", "label": "Prometheus Datasource", "query": "prometheus" },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(nats_core_jetstream_enabled, server_name)"
    }
   },
   {
    "name": "stream",
    "label": "Stream",
    "query": {
     "query": "label_values(nats_stream_consumer_count, stream_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nats_core_jetstream_memstore_used_bytes{server_name=~\"$server\"} / nats_core_jetstream_server_max_memory{server_name=~\"$server\"}",
     "legendFormat": "{{server_name}}"
    },
    { "legendFormat": "{{server_name}}" }
   ]
  },
  {
   "title": "Storage Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nats_core_jetstream_filestore_used_bytes{server_name=~\"$server\"} / nats_core_jetstream_server_max_storage{server_name=~\"$server\"}",
     "legendFormat": "{{server_name}}"
    },
    { "legendFormat": "{{server_name}}" }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nats_core_connection_count{server_name=~\"$server\"}",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Total Consumers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nats_core_jetstream_server_total_consumers{server_name=~\"$server\"}",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Total Storage Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nats_core_jetstream_filestore_used_bytes{server_name=~\"$server\"}",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Max Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nats_core_jetstream_server_max_storage{server_name=~\"$server\"}",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nats_core_jetstream_memstore_used_bytes{server_name=~\"$server\"}",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nats_core_jetstream_server_max_memory{server_name=~\"$server\"}",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  { "title": "Stream metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Stream data size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nats_stream_total_bytes{stream_name=~\"$stream\"}",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "Stream message count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nats_stream_total_messages{stream_name=~\"$stream\"}",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "Message Rate (per second)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "nats_core_jetstream_server_total_messages{server_name=~\"$server\"}",
     "legendFormat": "{{stream_name}}"
    }
   ]
  }
 ]
}