{
 "title": "NATS Servers",
 "description": "NATS Server Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prom_ds", "label": "Prometheus Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "OS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "nats_core_cpu_percentage", "legendFormat": "{{server_name}}" }
   ]
  },
  {
   "title": "Server Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "nats_core_mem_bytes", "legendFormat": "{{server_name}}" }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "nats_core_recv_bytes", "legendFormat": "{{server_name}}" }
   ]
  },
  {
   "title": "NATS Msgs In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nats_core_recv_msgs_count", "legendFormat": "{{server_name}}" }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "nats_core_sent_bytes", "legendFormat": "{{server_name}}" }
   ]
  },
  {
   "title": "NATS Msgs Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nats_core_sent_msgs_count", "legendFormat": "{{server_name}}" }
   ]
  },
  { "title": "Client Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nats_core_connection_count", "legendFormat": "{{server_name}}" }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nats_core_subs_count", "legendFormat": "{{server_name}}" }
   ]
  },
  {
   "title": "Slow Consumers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nats_core_slow_consumer_count", "legendFormat": "{{server_name}}" }
   ]
  }
 ]
}